version: '3.4'
services:
  ropsten.dnp.dappnode.eth:
    image: 'ropsten.dnp.dappnode.eth:0.3.3'
    build: ./build
    volumes:
      - 'ropsten:/root/.ethereum/'
    ports:
      - '30303'
      - 30303/udp
      - 30304/udp
    restart: always
    environment:
      - 'EXTRA_OPTS=--rpcapi eth,net,web3,txpool'
volumes:
  ropsten: {}
